redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "D:\\claude project\\internetblessing\\website\\frontend\\build"
publishOrigin = "config"
commandOrigin = "config"
base = "D:\\claude project\\internetblessing\\website\\frontend"
command = "npm run build"

[build.environment]
CI = "false"
REACT_APP_API_URL = "https://internetblessing-api.up.railway.app"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]